# Generated by Django 3.2.12 on 2022-03-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_replycomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='story',
            name='code',
        ),
    ]
