# Generated by Django 3.2.12 on 2022-03-14 09:13

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20220314_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='story',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
