# Generated by Django 3.2.12 on 2022-03-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20220314_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='num_participants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
