# Generated by Django 3.2.12 on 2022-02-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_bloglike'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
