# Generated by Django 3.2.12 on 2022-03-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_total_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='total_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
