# Generated by Django 3.2.12 on 2022-03-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_safe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
