import Head from 'next/head'
import {getListPostForumAPI} from '../../apis/userAPI'
import Link from "next/link";
import {FORUM} from "../../constants";

export async function getStaticProps() {
    const data = await getListPostForumAPI(1)
    return { props: data.data }
}

export default function Home(props) {
    console.log(props)
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="mx-auto w-10/12">
                <div className="mt-2.5">
                    <a className="mr-1.5" href="">Trang chủ</a>/
                    <a className="ml-1.5" href="">Diễn đàn</a>
                </div>
                <div className="font-bold text-2xl mt-2.5 flex items-center justify-between">
                    <div>Diễn Đàn Vietnovel Origin</div>
                    <div
                        className="">
                        <Link href="/forum/create">
                            <a className="no-underline color text-blue-400 text-xl font-normal">
                                <i className="bi bi-pencil-square mr-2.5"></i>
                                <span className="font-bold text-3xl">+</span> Mới
                            </a>
                        </Link>
                    </div>
                </div>
                <div
                    className="text-red-500 text-xl border-b border-solid border-red-500 mb-12 font-bold mt-12">
                    DANH SÁCH CÁC BÀI VIẾT
                </div>
                {props.items.map((value, index) => {
                    console.log(value.category)
                    return (
                        <div key={index} className="row">
                            <div
                                className="p-2.5 flex py-2.5 border border-solid border-gray-500 rounded-md shadow col mb-4">
                                <img className="w-20 h-32 rounded-md"
                                     src="https://static.khoibut.com/img/kb-novel-cover-default.jpg" alt="img"/>
                                <div className="ml-5">
                                    <div className="text-xl font-bold text-orange-300">
                                        <Link className="text-orange-300 underline"
                                              href={`${FORUM}${value?.code}`}>{value?.title}</Link>
                                    </div>
                                    <div>{value?.content}</div>
                                    <div className="flex mt-2.5">
                                        {value?.category.map((data_category, index) => (
                                            <div key={index}
                                                className="mr-1.5 bg-green-100 rounded-md text-green-700 py-0.5 px-2.5">
                                                {data_category}
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        </div>
                    )
                })}
            </div>
        </>
    )
}

