import Head from 'next/head'
import BlogDetail from '../../components/BlogDetail'
import { getBlogDetailAPI, getBlogDetailListAPI } from  '../../apis/userAPI'
import { useRouter } from "next/router";

export async function getServerSideProps(context) {
    // const { page } = context.query
    const { slug } = context.params
    const data = await getBlogDetailAPI(slug)
    const data2 = await getBlogDetailListAPI(slug)
    return {
        props: {
            blogDetail: data.data,
            blogDetailList: data2.data
        }
    }
}

export default function Home(props) {
    const router = useRouter()
    const { slug,page } = router.query
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <BlogDetail data={ props } />
        </>
    )
}

