import Head from 'next/head'
import BlogList from '../../components/BlogList'
import {getBlogListAPI} from '../../apis/userAPI'

export async function getStaticProps() {
    const data = await getBlogListAPI()
    return { props: data.data }
}

export default function Home(props) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <BlogList data={props} />
        </>
    )
}
