import Head from 'next/head'
import {useState} from "react";

// export async function getStaticProps() {
//     const data = await submitLoginAPI()
//     return {props: data.data}
// }

export default function Home(props) {

    const [valueFullName, setValueFullName] = useState('')
    const [valuePassword, setValuePassword] = useState('')

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <form className="w-full max-w-sm m-auto mt-20">
                <div className="md:flex md:items-center mb-6">
                    <div className="md:w-1/3">
                        <label className="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4"
                               htmlFor="inline-full-name">
                            Họ và tên
                        </label>
                    </div>
                    <div className="md:w-2/3">
                        <input
                            onChange={(e) => {setValueFullName(e.target.value)}}
                            className="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                            id="inline-full-name" type="text" placeholder="Nguyễn Văn A" value={valueFullName}/>
                    </div>
                </div>
                <div className="md:flex md:items-center mb-6">
                    <div className="md:w-1/3">
                        <label className="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4"
                               htmlFor="inline-password">
                            Mật khẩu
                        </label>
                    </div>
                    <div className="md:w-2/3">
                        <input
                            onChange={(e) => {setValuePassword(e.target.value)}}
                            className="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                            id="inline-password" type="password" value={valuePassword} placeholder="******************"/>
                    </div>
                </div>
                <div className="md:flex md:items-center">
                    <div className="md:w-1/3"></div>
                    <div className="md:w-2/3">
                        <button
                            className="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded"
                            type="button">
                            Đăng Nhập
                        </button>
                    </div>
                </div>
            </form>
        </>
    )
}
